---
require: 'rubocop-rails'
AllCops:
  Exclude:
    - bin/**/*
    - examples/**/*
    - Rakefile
  TargetRubyVersion: 2.3
Metrics/LineLength:
  Max: 100
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'tshield.gemspec'
Rails:
  Enabled: false
