---
AllCops:
  Exclude:
    - bin/**/*
    - examples/**/*
    - Guardfile
    - Rakefile
  TargetRubyVersion: 2.4
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'tshield.gemspec'
