language: ruby
rvm:
  - 2.2

notifications:
  email:
    - rubin.diego@gmail.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b4269c243a6f38e0d635
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

gemfile:
  - Gemfile

script: bundle exec rspec
