source "https://rubygems.org"

gem 'capybara'
gem 'cucumber'
gem 'httparty'
gem 'rspec'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'tshield'
gem 'webdrivers'

group :development do
  gem 'rubocop'
  gem 'byebug'
end

