#!/bin/bash

cd component_tests
./server &
SERVER=$!

../bin/tshield -c config.yml &
TSHIELD=$!

sleep 10

cd ..
cucumber
export STATUS="$?"

echo "killing server($SERVER) tshield($TSHIELD)"
kill $SERVER $TSHIELD

exit $STATUS
