#!/bin/bash

cd component_tests
ruby server.rb &
SERVER=$!

ruby grpc_server.rb &
GRPC_SERVER=$!

../bin/tshield -c config.yml &

sleep 5

cd ..
cucumber
export STATUS="$?"

echo "killing server($SERVER) server($GRPC_SERVER)"
kill $SERVER $GRPC_SERVER

exit $STATUS
